name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run script
        run: |
          myimage=basoyan/python:v0.0.1
          docker login -u basoyan -p ${{ secrets.DOCKER_TOKEN }}
          docker build -t $myimage -f Dockerfile-app .
          docker push $myimage

