name: My Action

on:
  push:
    branches:
      - main
env:
  DOCKER_USERNAME: basoyan
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  IMAGE_NAME: basoyan/python-app:v0.0.1
  DOCKER_FILE: Dockerfile-app
  DOCKER_CONTEXT: ./

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{ env.DOCKER_CONTEXT }}
          file: ${{ env.DOCKER_FILE }}
          tags: ${{ env.IMAGE_NAME }}
          push: true


