name: "Test Github Actions"

on:
  push:
    branches:
      - main


jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Something
        run: |-
           echo "This my variable: ${{ vars.MY_VAR }}"
           echo "This my secret: ${{ secrets.MY_SECRET }}"




