name: "Test Github Actions"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Something
        run: |-
           echo "Hello World"
           echo "This is a test"
           ls -la
           cat myfile.txt

