name: "Test Github Actions"

on:
  push:
    branches:
      - main

env:
  MY_VAR: "Hello World"

jobs:
  test-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Something
        run: |-
           echo $MY_VAR

  test-2:
    runs-on: ubuntu-latest
    env:
      MY_VAR: "Goodbye World"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Something
        run: |-
           echo ${{ env.MY_VAR }}


